### ISSUE TITLE
Tagging a release

### ISSUE THREAD

**Issue by ScrumpyJack** [vandry/mairix#1]
hi kim. could you tag a release so that matrix can be packaged easily?
Something like

`git tag -a v0.24 -m "kim's version"`

thanks

**Comment by vandry** [comment]
Hi,

I would like very much to release a new version of mairix but I would like to make it the official one if possible, so that there are not two published versions and so that software distributions such as Debian will package my version by default.

Please raise the issue on the mailing list. Although the original author was not heard from in quite some time, he did chime in once last Summer. I requested ownership of the project ( https://sourceforge.net/p/mairix/mailman/message/34293828/ ) but did not hear back. Perhaps if you ask again nicely this can get done. I would then resurrect the web site (most likely, just make Github the project home), merge my changes, ask anyone else if they have issues I could look into, release  a new version, and ask Debian to upgrade to the new version.

If you do not wish to subscribe to the mailing list, I will ping it again one last time. If that still doesn't work, I can consider forking the project officially.

**Comment by ScrumpyJack** [comment]
Yes I saw that. "I think I would be willing to take it over."
Earlier, the original author said: "[mairix] can be considered as orphaned.  If anyone
wants to take it over, feel free"
I think it's safe for you to take over and maintain the project. 
Great little tool by the way. Nothing else quite like it. I use it daily.

**Comment by vandry** [comment]
I will do this in the next couple of weeks

**Comment by spwhitton** [comment]
I'm the de facto maintainer of mairix in Debian.  I would love to see new releases.  I hope you can merge the patches we're carrying, such as https://github.com/rc0/mairix/pull/20

**Comment by vandry** [comment]
spwhitton, all of the patches from Debian mairix-0.23+git20131125 are now either merged or obsolete.

Let me have a short run through the other open issues and pull requests and then I'll make a release and you can get it in Debian.

**Comment by vandry** [comment]
I have finished fixing all of the issues I intend to fix in the immediate term. 4 of the remaining issues require more work:

- rc0/mairix#25 and rc0/mairix#21: look into making mairix lockless
- rc0/mairix#23 and rc0/mairix#12: look into changing/upgrading some data types to remove size limitations.

And the other two issues are wishlist items and probably won't be done at all:

- rc0/mairix#15: accented characters support
- rc0/mairix#13: Option to search specified headers

I've run out of time to actually make the realease this weekend, but it'll be soon.

**Comment by spwhitton** [comment]
Thanks for the update!

-- 
Sean Whitton

**Comment by vandry** [comment]
Done.

**Comment by ericpruitt** [comment]
@vandry wrote:
> And the other two issues are wishlist items and probably won't be done at all:
> - rc0/mairix#13: Option to search specified headers

Is the likely to not be implemented simply because you don't have the time? Would you be willing to merge this feature if someone else implemented it?

**Comment by vandry** [comment]
Hi Eric,

Time and motivation isn't the only reason. I haven't looked into it in detail, but I expect to find that mairix indexes each of the main fields on which lookups can be done (like from, to, date, subject, size, flags, attachment names, and body) separately in the index. Allowing search on arbitrary headers would probably mean a proliferation of new types of fields in the index, which comes with a size and time cost for building (and possibly searching) the index. I'm not sure that would be a good tradeoff to make.

I will consider any well-designed patches if someone wants to implement this feature, but be warned that I will bear the aforementioned concern in mind during review. Ideally, I am totally wrong, and this can be done both efficiently and cleanly, and I will be happy to merge the result.

-kv

**Comment by ericpruitt** [comment]
> I expect to find that mairix indexes each of the main fields on which lookups can be done (like from, to, date, subject, size, flags, attachment names, and body) separately in the index.

Yeah -- I looked at the implementation already, and that's correct assuming I didn't misinterpret the code. The approach I was considering was to create a single new field in the database -- let's say it's called "misc" -- that would store tokens for **all** of the headers that don't have a dedicated index. Doing lookups for specific tokens in the "misc" field would be less efficient than the lookups for the headers that have their own indexes, but I think it wouldn't be a problem in practice since searching for text is arbitrary headers isn't what users typically want to do.

**Comment by vandry** [comment]
That sounds very reasonable. I agree. I look forward to reviewing your code.

Please follow up on the issue opened for that feature request: https://github.com/rc0/mairix/issues/13

**Comment by ericpruitt** [comment]
Done. This message may be redundant; I "@" mentioned you, but you weren't added to the notification list and I'm not sure when / how GitHub chooses to notify people of new messages, so I'm following up here just to make sure you're aware of my [new comment](https://github.com/rc0/mairix/issues/13#issuecomment-353763205) which fleshes out more details than I provided here.
