### ISSUE TITLE
Odd numbering of search results with mformat=mh

### ISSUE THREAD

**Issue by ConradHughes** [vandry/mairix#16]
Hi there,

[using Debian's mairix 0.24-2]

mairix looks amazingly useful; I'm embarrassed to have not tried it many years ago.

One question, on something I can't find any information on in the man pages: search results in MH format ("mformat=mh") produce a folder with really wild message numbers — e.g. my last search got results numbered 7091 and 7094.  There's nothing to stop me renumbering the folder after running a search, but it seems odd; is there a reason for this, or a way to make mairix number them consecutively from 1?

Best,
Conrad

**Comment by ConradHughes** [comment]
.. on the face of it, all that *seems* to be needed to fix this appears to be changing the use of 'i' (database index number) to 'n_hits' in calls to mk_mh_path() in do_search().

**Comment by vandry** [comment]
I guess this might have been done so that the same email always gets the same filename in search results (as long as the index is not rebuilt). MUAs might recognise it as the same email after the search results mailbox has been cleared and reinitialized.

In any case your commit aa4ae41b53b9c95747f5a3511e621f2722dc9d89 resolves this.
